/**
 * Tool Registry Loader — Build-time code generation.
 *
 * Scans tool directories, parses YAML manifests, and generates
 * a TypeScript file with all tool definitions baked in.
 *
 * Run: pnpm run build:tools
 *
 * Why build-time? Cloudflare Workers have no filesystem access
 * at runtime. This pattern is common in edge runtimes.
 */

import fs from "node:fs";
import path from "node:path";
import yaml from "yaml";

interface ToolManifest {
  name: string;
  description: string;
  category: "hot" | "blocks" | "zones" | "content" | "publish";
  parameters: {
    type: "object";
    properties: Record<string, any>;
    required?: string[];
  };
}

interface DiscoveredTool {
  name: string;
  description: string;
  category: string;
  parameters: Record<string, any>;
  required: string[];
  dirName: string;
}

const TOOLS_DIR = "./src/agents/tools";
const OUTPUT_FILE = path.join(TOOLS_DIR, "registry.generated.ts");

function discoverTools(): DiscoveredTool[] {
  const tools: DiscoveredTool[] = [];

  const entries = fs.readdirSync(TOOLS_DIR, { withFileTypes: true });

  for (const entry of entries) {
    if (!entry.isDirectory()) continue;

    const yamlPath = path.join(TOOLS_DIR, entry.name, "tool.yaml");
    const handlerPath = path.join(TOOLS_DIR, entry.name, "handler.ts");

    // Skip directories without both files
    if (!fs.existsSync(yamlPath) || !fs.existsSync(handlerPath)) continue;

    const yamlContent = fs.readFileSync(yamlPath, "utf-8");
    let manifest: ToolManifest;

    try {
      manifest = yaml.parse(yamlContent);
    } catch (err) {
      console.error(`  ✗ Failed to parse ${yamlPath}:`, err);
      continue;
    }

    // Validate required manifest fields
    if (!manifest.name || !manifest.description || !manifest.category) {
      console.error(`  ✗ Missing required fields in ${yamlPath}`);
      continue;
    }

    tools.push({
      name: manifest.name,
      description: manifest.description,
      category: manifest.category,
      parameters: manifest.parameters?.properties ?? {},
      required: manifest.parameters?.required ?? [],
      dirName: entry.name,
    });
  }

  return tools;
}

function generateRegistryFile(tools: DiscoveredTool[]): string {
  // Build import statements
  const imports = tools
    .map((t) => {
      // Handle tool names with underscores (e.g., ask_user → askUserHandler)
      const handlerName = t.name.replace(/_([a-z])/g, (_, c) => c.toUpperCase());
      return `import { handler as ${handlerName}Handler } from "./${t.dirName}/handler";`;
    })
    .join("\n");

  // Build tool definitions array
  const definitions = tools
    .map((t) => {
      const handlerName = t.name.replace(/_([a-z])/g, (_, c) => c.toUpperCase());
      return `  {
    name: "${t.name}",
    description: ${JSON.stringify(t.description)},
    category: "${t.category}" as const,
    parameters: ${JSON.stringify(t.parameters, null, 4).replace(/\n/g, "\n    ")},
    required: ${JSON.stringify(t.required)},
    handler: ${handlerName}Handler,
  }`;
    })
    .join(",\n");

  return `/**
 * Auto-generated tool registry — DO NOT EDIT.
 *
 * Generated by: pnpm run build:tools
 * Source: src/agents/tools/loader.ts
 *
 * ${tools.length} tools registered from ${tools.length} directories.
 */

import type { ToolHandler } from "./types";

${imports}

export const TOOL_DEFINITIONS = [
${definitions},
];
`;
}

// --- Main ---

console.log("Building tool registry...");

const tools = discoverTools();

if (tools.length === 0) {
  console.error("  ✗ No tools found! Check src/agents/tools/ directories.");
  process.exit(1);
}

const output = generateRegistryFile(tools);
fs.writeFileSync(OUTPUT_FILE, output, "utf-8");

// Summary
const hotCount = tools.filter((t) => t.category === "hot").length;
const deferredCount = tools.length - hotCount;
console.log(`  ✓ ${tools.length} tools (${hotCount} hot, ${deferredCount} deferred)`);
console.log(`  ✓ Written to ${OUTPUT_FILE}`);
